name: Publish
on:
  push:
    tags:
      - "v*" # Trigger for tags starting with 'v'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Use Cached Dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test

      - name: Build Library
        run: pnpm run build

      - name: Configure .npmrc
        run: |
          echo "@tarektarho:registry=https://npm.pkg.github.com" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_TOKEN }}" >> ~/.npmrc

      - name: Publish Library
        run: npm publish --access public